name: Node.js Backend Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Deploy to DigitalOcean
        run: |
          eval $(ssh-agent -s)
          ssh-add <(echo "SHA256:fKFtGpiB+j4+XfQM8g6uKinpF6toPi8U20wPMSaw+Fg")
          ssh root@159.65.255.38 'cd Smash-Moment-Alpha/ && git pull origin main && npm install && pm2 restart server.js'
