name: Node.js Backend Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          
      - name: Print SSH_PRIVATE_KEY
        run: echo "SSH_PRIVATE_KEY is ${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Verify Host Key
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: ssh -o "StrictHostKeyChecking accept-new" root@159.65.255.38 "echo 'SSH connection successful'"
      # - name: Deploy to DigitalOcean
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #   run: |
      #     ssh root@159.65.255.38 'cd Smash-Moment-Alpha/ && git pull origin main && npm install && pm2 restart server.js'
        
